version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin <your_ecr_repository_url>
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t lastname-app .
      - echo Tagging the image...
      - docker tag lastname-app:latest <your_ecr_repository_url>/lastname-app:latest
      - echo Pushing the Docker image to ECR...
      - docker push <your_ecr_repository_url>/lastname-app:latest
